# Generated by Django 4.2.2 on 2023-08-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="job",
            field=models.CharField(
                choices=[("gardener", "Gardener"), ("arborist", "Arborist")],
                default="gardener",
                max_length=10,
            ),
        ),
    ]
