# Generated by Django 4.2.2 on 2023-08-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_alter_employee_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="job",
            field=models.CharField(
                choices=[
                    ("gardener", "Gardener"),
                    ("arborist", "Arborist"),
                    ("manager", "Manager"),
                ],
                default="gardener",
                max_length=10,
            ),
        ),
    ]
