# Generated by Django 4.2.2 on 2023-08-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="last_watered",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
